---
name: Netboot XYZ w/ Customized Startup
# This dockerfile is a starting point for custom startup processes.
# When running thru ./start.sh, it generates hook files for the built-in
# - start.sh
# - init.sh
# - dnsmasq.conf
# - supervisor.conf (see ./state/extra/etc/supervisor.conf for an example that pipes everything to stdout)
#
# See other examples for more complete setups.

services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    command: sh /extra/start.sh
    environment:
      MENU_VERSION: "2.0.47" # optional
      NGINX_PORT: "80" # optional
      WEB_APP_PORT: "3000" # optional
      TFTPD_OPTS: "--conf-file=/extra/etc/dnsmasq.conf"
    volumes:
      - ./state/config:/config
      - ./state/assets:/assets
      - ./state/extra:/extra
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80
    restart: unless-stopped