---
name: Netboot XYZ - dnsmasq DHCP-proxy
# This dockerfile takes the contents of the "Add DHCP-proxy support" PR
# and adjusts them to hook into the flow from the `customized-startup` example
# https://github.com/netbootxyz/docker-netbootxyz/pull/73

services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    command: sh /extra/start.sh
    environment:
      # MENU_VERSION: "2.0.47" # optional
      # NGINX_PORT: "80" # optional
      # WEB_APP_PORT: "3000" # optional
      TFTPD_OPTS: "--conf-file=/extra/etc/dnsmasq.conf "
      DHCP_RANGE_START: 192.168.11.1
      LAN_IP: 192.168.11.1
    volumes:
      - ./state/config:/config
      - ./state/assets:/assets
      - ./state/extra:/extra
    restart: unless-stopped
    cap_add:
      - NET_ADMIN # required for DHCP Proxy mode.
    network_mode: host # required for DHCP Proxy mode.